global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'inventory-service'
    scrape_interval: 2s
    metrics_path: '/inventory-service/actuator/prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9010' ]